/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { DividendTickersRequest } from '../model/dividend-tickers-request';
// @ts-ignore
import { DividendTickersResponse } from '../model/dividend-tickers-response';
// @ts-ignore
import { HTTPValidationError } from '../model/http-validation-error';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface ListDividendTickersApiDividendsUniqueTickersPostRequestParams {
    dividendTickersRequest: DividendTickersRequest;
}


@Injectable({
  providedIn: 'root'
})
export class DatabaseApiService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * List unique dividend payers (DB-backed)
     * Returns unique tickers paying dividends at the requested frequency from the internal &#x60;dividends&#x60; collection.  - **frequency**: 0 (one-time), 1 (annual), 2 (semi-annual), 4 (quarterly), 12 (monthly), 24 (bi-monthly), 52 (weekly). - **dividend_type**: e.g. [\&quot;CD\&quot;] for regular cash dividends, [\&quot;SC\&quot;] for special. - **include_market**: if true (default), each row includes the &#x60;market&#x60; looked up from &#x60;tickers&#x60;. - Sorted alphabetically by ticker; paginated with &#x60;page&#x60; / &#x60;page_size&#x60;.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listDividendTickersApiDividendsUniqueTickersPost(requestParameters: ListDividendTickersApiDividendsUniqueTickersPostRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<DividendTickersResponse>;
    public listDividendTickersApiDividendsUniqueTickersPost(requestParameters: ListDividendTickersApiDividendsUniqueTickersPostRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<DividendTickersResponse>>;
    public listDividendTickersApiDividendsUniqueTickersPost(requestParameters: ListDividendTickersApiDividendsUniqueTickersPostRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<DividendTickersResponse>>;
    public listDividendTickersApiDividendsUniqueTickersPost(requestParameters: ListDividendTickersApiDividendsUniqueTickersPostRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const dividendTickersRequest = requestParameters?.dividendTickersRequest;
        if (dividendTickersRequest === null || dividendTickersRequest === undefined) {
            throw new Error('Required parameter dividendTickersRequest was null or undefined when calling listDividendTickersApiDividendsUniqueTickersPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/dividends/unique-tickers`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<DividendTickersResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: dividendTickersRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
