/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Provenance } from './provenance';
import { ProvenanceToolCall } from './provenance-tool-call';


export interface AgentUIResponseProvenance { 
    tools?: Array<ProvenanceToolCall>;
    extra?: { [key: string]: any; };
}

