/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentUI } from './agent-ui';
import { RequestId } from './request-id';
import { AgentUIResponseProvenance } from './agent-ui-response-provenance';


/**
 * Full response the backend returns to the Angular app or that the `format_response` tool validates and returns.  Contract: - `html`: short, safe HTML snippet (rendered in the left/top panel) - `ui`: structured payload for PrimeNG tables/charts/badges - `provenance`: optional tool-call trace for transparency - `request_id`: optional correlation ID for logs  Backward-compat: - We also accept *top-level* `tables`, `charts`, `badges`, `sections`, and `meta`.   They will be normalized into `ui.tables`, `ui.charts`, `ui.badges`, `ui.sections`, and `ui.meta`.
 */
export interface AgentUIResponse { 
  [key: string]: any | any;


    request_id?: RequestId;
    /**
     * Short HTML summary for the user.
     */
    html: string;
    ui?: AgentUI;
    provenance?: AgentUIResponseProvenance;
}

