/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UITable } from './ui-table';
import { ChartSpec } from './chart-spec';
import { UIBadge } from './ui-badge';
import { UIMeta } from './ui-meta';


/**
 * Structured UI payload the frontend binds to. - tables: list of table specs - charts: list of chart specs - badges: quick labels/metrics - meta: top-level metadata (ticker, asOf, notes)
 */
export interface AgentUI { 
  [key: string]: any | any;


    meta?: UIMeta;
    tables?: Array<UITable>;
    charts?: Array<ChartSpec>;
    badges?: Array<UIBadge>;
}

