/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V } from './v';


export interface AggBar { 
    t: number;
    o: number;
    h: number;
    l: number;
    c: number;
    v: V;
    n?: number | null;
    vw?: number | null;
}

