/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BalanceFlat { 
    assets?: number | null;
    current_assets?: number | null;
    inventory?: number | null;
    other_current_assets?: number | null;
    noncurrent_assets?: number | null;
    fixed_assets?: number | null;
    other_noncurrent_assets?: number | null;
    liabilities?: number | null;
    current_liabilities?: number | null;
    accounts_payable?: number | null;
    other_current_liabilities?: number | null;
    noncurrent_liabilities?: number | null;
    long_term_debt?: number | null;
    equity?: number | null;
    liabilities_and_equity?: number | null;
}

