/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CashflowFlat { 
    net_cash_flow_from_operating_activities?: number | null;
    net_cash_flow_from_investing_activities?: number | null;
    net_cash_flow_from_financing_activities?: number | null;
    net_cash_flow?: number | null;
}

