/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChartDataset } from './chart-dataset';


/**
 * Chart.js data payload.
 */
export interface ChartData { 
    labels: Array<string>;
    datasets: Array<ChartDataset>;
}

