/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Options } from './options';
import { ChartData } from './chart-data';
import { Title } from './title';


/**
 * A single chart card the UI can render via <p-chart>.
 */
export interface ChartSpec { 
  [key: string]: any | any;


    id: string;
    type: ChartSpecTypeEnum;
    title?: Title;
    data: ChartData;
    options?: Options;
}
export enum ChartSpecTypeEnum {
    bar = 'bar',
    line = 'line',
    pie = 'pie',
    doughnut = 'doughnut',
    radar = 'radar',
    polarArea = 'polarArea'
};



