/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComprehensiveFlat { 
    comprehensive_income_loss?: number | null;
    other_comprehensive_income_loss_attributable_to_parent?: number | null;
}

