/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum DataQuality {

    ok = 'ok',

    estimated = 'estimated',

    missing_fields = 'missing_fields'
}

