/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * List unique dividend payers (tickers) for a given frequency. Defaults to monthly payers (12). You can optionally bound by ex_dividend_date window.
 */
export interface DividendTickersRequest { 
    frequency?: number;
    ex_dividend_date_from?: string | null;
    ex_dividend_date_to?: string | null;
    dividend_type?: Array<string> | null;
    page?: number;
    page_size?: number;
    include_market?: boolean;
}

