/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DividendTickerItem { 
    ticker: string;
    count: number;
    last_ex_dividend_date?: string | null;
    market?: string | null;
}

