/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DividendDoc } from './dividend-doc';


export interface DividendSearchResponse { 
    total: number;
    company_name: string;
    page: number;
    page_size: number;
    results: Array<DividendDoc>;
}

