/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DividendDoc { 
    id?: string | null;
    ticker: string;
    cash_amount: number;
    currency?: string | null;
    frequency?: number | null;
    dividend_type?: DividendDocDividendTypeEnum | null;
    ex_dividend_date?: string | null;
    record_date?: string | null;
    declaration_date?: string | null;
    pay_date?: string | null;
    m?: { [key: string]: any; } | null;
}
export enum DividendDocDividendTypeEnum {
    CD = 'CD',
    SC = 'SC',
    LT = 'LT',
    ST = 'ST'
};



