/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ratios } from './ratios';
import { IncomeFlat } from './income-flat';
import { CashflowFlat } from './cashflow-flat';
import { BalanceFlat } from './balance-flat';
import { PeriodFlags } from './period-flags';
import { ComprehensiveFlat } from './comprehensive-flat';
import { SourceRef } from './source-ref';
import { FiscalPeriod } from './fiscal-period';


export interface FinancialPeriod { 
    fiscal_year: number;
    fiscal_period?: FiscalPeriod | null;
    period_end_date: string;
    income?: IncomeFlat | null;
    balance?: BalanceFlat | null;
    cashflow?: CashflowFlat | null;
    comprehensive?: ComprehensiveFlat | null;
    ratios?: Ratios | null;
    sources?: Array<SourceRef> | null;
    flags?: PeriodFlags | null;
}



