/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FinancialPeriod } from './financial-period';
import { Meta } from './meta';
import { RangeBlock } from './range-block';


export interface FinancialsTimeseriesResponse { 
    meta: Meta;
    range: RangeBlock;
    periods: Array<FinancialPeriod>;
}

