/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecentQuarter } from './recent-quarter';
import { TTMBlock } from './ttm-block';
import { HistoryTTMPoint } from './history-ttm-point';


export interface FinancialsHistory { 
    ttm_points?: Array<HistoryTTMPoint>;
    ttm_prev?: TTMBlock | null;
    recent_quarters?: Array<RecentQuarter>;
}

