/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meta } from './meta';


export interface FinancialsRatiosResponse { 
    meta: Meta;
    periods: Array<{ [key: string]: any; }>;
}

