/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FinancialPeriod } from './financial-period';
import { Meta } from './meta';
import { SummaryDeltas } from './summary-deltas';
import { TTMBlock } from './ttm-block';
import { FinancialsHistory } from './financials-history';


export interface FinancialsSummaryResponse { 
    meta: Meta;
    latest: FinancialPeriod;
    trailing_twelve_months?: TTMBlock | null;
    deltas?: SummaryDeltas | null;
    history?: FinancialsHistory | null;
}

