/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum FiscalPeriod {

    Q1 = 'Q1',

    Q2 = 'Q2',

    Q3 = 'Q3',

    Q4 = 'Q4',

    FY = 'FY'
}

