/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum of standard GICS sectors for use in mappings and dropdowns.
 */
export enum GICSSector {

    Energy = 'Energy',

    Materials = 'Materials',

    Industrials = 'Industrials',

    Consumer_Discretionary = 'Consumer Discretionary',

    Consumer_Staples = 'Consumer Staples',

    Health_Care = 'Health Care',

    Financials = 'Financials',

    Information_Technology = 'Information Technology',

    Communication_Services = 'Communication Services',

    Utilities = 'Utilities',

    Real_Estate = 'Real Estate'
}

