/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoryTTMPoint { 
    period_end_date: string;
    revenues?: number | null;
    gross_profit?: number | null;
    operating_income?: number | null;
    net_income?: number | null;
    operating_cash_flow?: number | null;
    free_cash_flow?: number | null;
}

