/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IncomeFlat { 
    revenues?: number | null;
    cost_of_revenue?: number | null;
    gross_profit?: number | null;
    operating_expenses?: number | null;
    selling_general_and_administrative_expenses?: number | null;
    research_and_development?: number | null;
    operating_income_loss?: number | null;
    nonoperating_income_loss?: number | null;
    income_tax_expense_benefit?: number | null;
    net_income_loss?: number | null;
    basic_earnings_per_share?: number | null;
    diluted_earnings_per_share?: number | null;
    basic_average_shares?: number | null;
    diluted_average_shares?: number | null;
}

