/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Periodicity } from './periodicity';


export interface Meta { 
    ticker: string;
    company_name?: string | null;
    currency?: string;
    unit?: MetaUnitEnum;
    periodicity: Periodicity;
    asof?: string | null;
    version?: string;
}
export enum MetaUnitEnum {
    absolute = 'absolute'
};



