/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MetricsSearchResponse { 
    total: number;
    page: number;
    page_size: number;
    results: Array<any>;
}

