/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NewsItem { 
    id?: string | null;
    title?: string | null;
    author?: string | null;
    description?: string | null;
    published_utc?: string | null;
    article_url?: string | null;
    image_url?: string | null;
    tickers?: Array<string> | null;
    source?: string | null;
}

