/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataQuality } from './data-quality';


export interface PeriodFlags { 
    restated?: boolean | null;
    partial_period?: boolean | null;
    data_quality?: DataQuality | null;
    notes?: string | null;
}



