/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Track each tool used to produce the view (for audit/debug display).
 */
export interface ProvenanceToolCall { 
    name: string;
    args?: { [key: string]: any; };
    duration_ms?: number | null;
    ok?: boolean | null;
    error?: string | null;
}

