/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProvenanceToolCall } from './provenance-tool-call';


/**
 * Optional provenance block to show sources and timings.
 */
export interface Provenance { 
  [key: string]: any | any;


    tools?: Array<ProvenanceToolCall>;
    extra?: { [key: string]: any; };
}

