/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Ratios { 
    gross_margin?: number | null;
    operating_margin?: number | null;
    net_margin?: number | null;
    current_ratio?: number | null;
    quick_ratio?: number | null;
    debt_to_equity?: number | null;
    return_on_assets?: number | null;
    return_on_equity?: number | null;
    revenue_yoy?: number | null;
    eps_yoy?: number | null;
    ocf_margin?: number | null;
    free_cash_flow?: number | null;
}

