/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RebuildPayload { 
    /**
     * Number of parallel workers
     */
    workers?: number;
    max_tickers?: number | null;
    per_ticker_limit?: number | null;
    throttle_ms?: number | null;
}

