/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RebuildAllResponse { 
    cutoff: string;
    collection: string;
    total_metrics_docs: number;
    status: string;
}

