/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FiscalPeriod } from './fiscal-period';


export interface RecentQuarter { 
    fiscal_year: number;
    fiscal_period?: FiscalPeriod | null;
    period_end_date: string;
    revenue?: number | null;
    operating_income?: number | null;
    net_income?: number | null;
    diluted_eps?: number | null;
    ocf?: number | null;
}



