/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SummaryDeltas { 
    revenue_qoq?: number | null;
    revenue_yoy?: number | null;
    eps_yoy?: number | null;
    net_income_yoy?: number | null;
}

