/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Small label chips to surface quick facts.
 */
export interface UIBadge { 
    label: string;
    severity?: UIBadgeSeverityEnum | null;
    tooltip?: string | null;
}
export enum UIBadgeSeverityEnum {
    info = 'info',
    success = 'success',
    warn = 'warn',
    danger = 'danger'
};



