/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Asof } from './asof';
import { Ticker } from './ticker';
import { Notes } from './notes';


/**
 * Optional metadata the UI can show (e.g., header badges/tooltips).
 */
export interface UIMeta { 
  [key: string]: any | any;


    ticker?: Ticker;
    asOf?: Asof;
    notes?: Notes;
}

