/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Column definition for PrimeNG <p-table>.
 */
export interface UITableColumn { 
    /**
     * Row object key.
     */
    field: string;
    /**
     * Column header title displayed in the UI.
     */
    header: string;
}

