/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UITableColumn } from './ui-table-column';


/**
 * Tabular data the Angular app can bind directly to PrimeNG.
 */
export interface UITable { 
    /**
     * Stable ID so Angular can track the table.
     */
    id: string;
    title?: string | null;
    columns: Array<UITableColumn>;
    rows?: Array<{ [key: string]: any; }>;
}

