/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertPayload { 
    /**
     * List of tickers to fetch/upsert
     */
    tickers: Array<string>;
    workers?: number;
}

